WAITFOR DELAY '00:00:03';
GO

GO
CREATE LOGIN [admin] WITH PASSWORD='Abcd1234', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [admin];
GO
WAITFOR DELAY '00:00:02';
GO
CREATE LOGIN [sql_helper] WITH PASSWORD='Abcd1234', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [sql_helper];
GO
WAITFOR DELAY '00:00:02';
GO


CREATE LOGIN [kafka_src] WITH PASSWORD='Abcd1234', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;
GO
WAITFOR DELAY '00:00:02';
GO
CREATE LOGIN [kafka_sink] WITH PASSWORD='Abcd1234', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;
GO
WAITFOR DELAY '00:00:02';
GO


CREATE LOGIN [seatunnel_src] WITH PASSWORD='Abcd1234', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;
GO
WAITFOR DELAY '00:00:02';
GO
CREATE LOGIN [seatunnel_sink] WITH PASSWORD='Abcd1234', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF;
GO
WAITFOR DELAY '00:00:02';
GO



